name: SBOM Security Scan

on:
  workflow_dispatch:

  schedule:
    - cron: '0 6 * * 1'
      timezone: "Europe/Berlin"

jobs:
  sbom-scan:
    runs-on: ubuntu-latest
    name: SBOM scan
    steps:
      - uses: actions/checkout@v6
      - name: Install grype
        shell: bash
        run: |
          wget https://github.com/anchore/grype/releases/download/v0.116.1/grype_0.116.1_linux_amd64.deb
          sudo dpkg -i *.deb
          sudo apt-get update
          sudo apt-get install -y colorized-logs
      - name: Scan SBOM
        shell: bash
        run: |
          mkdir -p report
          dirs=
          for dir in linux viewit; do
            cd $dir
            sboms=$(ls *-sbom.cdx.json)
            while IFS= read -r sbom; do
              echo "Scanning $sbom..."
              image=$(basename $sbom -sbom.cdx.json)
              CLICOLOR_FORCE=true grype sbom:$sbom --file $image.txt --by-cve
              DISTRO=$(jq -r '.components[] | select(.name == "libc6") | .purl' $sbom | grep -o 'distro=[^&]*')
              if [[ "$DISTRO" = *"debian"* ]]; then
                  # URL="https:\/\/security-tracker.debian.org\/tracker\/"
                  URL="https:\/\/deb.freexian.com\/extended-lts\/tracker\/"
              elif [[ "$DISTRO" = *"ubuntu"* ]]; then
                  URL="https:\/\/ubuntu.com\/security\/"
              else
                  URL="https:\/\/www.cve.org\/CVERecord?id="
              fi
              (echo -e "\e[1m\e[4mCVE report for $image - $(date --rfc-3339=date)\e[0m\n" && cat $image.txt) | ansi2html --title "CVE $image" --no-wrap --style 'a {color: white;}' | sed -E "s/(CVE-[0-9]{4}-[0-9]{4,7})/<a href=\"$URL\1\">\1<\/a>/g" > ../report/$image.html
            done <<< "$sboms"
            cd ..
          done
      - name: Generate Markdown File
        run: |
          echo "name: SBOMs and Vulnerability Reports" > report/_config.yml
          echo "title: null" >> report/_config.yml
          cat << 'EOF' > report/index.md
          # IMAGO Technologies SBOMs and Vulnerability Reports

          SBOMs are provided in CycloneDX JSON format.

          All SBOMs are scanned for known vulnerabilities on a regular basis using [grype](https://github.com/anchore/grype).
          The vulnerability report contains a table with affected packages and the CVE names. Each entry also contains a link to the
          Security Bug Tracker of the used Linux distribution which provides more information.

          *Resources:*
          - [CVE database](https://www.cve.org/)
          - [Debian Security Bug Tracker](https://deb.freexian.com/extended-lts/tracker/)
          - [Ubuntu CVEs](https://ubuntu.com/security/cves)

          ## Linux Images

          EOF
          echo "| Linux Image | SBOM | Vulnerability Report ($(date --rfc-3339=date)) |" >> report/index.md
          echo "| :--- | :--- | :--- |" >> report/index.md
          cd linux
          sboms=$(ls *-sbom.cdx.json)
          while IFS= read -r sbom; do
            file=$(basename $sbom -sbom.cdx.json)
            echo "|$file|[$sbom](https://github.com/IMAGO-Technologies/sbom-scan/blob/master/linux/$sbom)|[$file]($file.html)|" >> ../report/index.md
          done <<< "$sboms"
          cd ..
          cat << 'EOF' >> report/index.md

          ## ViewIT

          The SBOM for ViewIT includes all dependencies for the package.

          EOF
          echo "| Package | Version | Architecture | SBOM | Vulnerability Report ($(date --rfc-3339=date)) |" >> report/index.md
          echo "| :--- | :--- | :--- | :--- | :--- |" >> report/index.md
          cd viewit
          sboms=$(ls *-sbom.cdx.json)
          while IFS= read -r sbom_file; do
            sbom_name=$(basename $sbom_file -sbom.cdx.json)
            deb_name=$(echo $sbom_name | cut -d '_' -f 1)
            version=$(echo $sbom_name | cut -d '_' -f 2)
            arch=$(echo $sbom_name | cut -d '_' -f 3)
            echo "|$deb_name|$version|$arch|[$sbom_file](https://github.com/IMAGO-Technologies/sbom-scan/blob/master/viewit/$sbom_file)|[$sbom_name]($sbom_name.html)|" >> ../report/index.md
          done <<< "$sboms"
      - name: Setup Pages Metadata
        uses: actions/configure-pages@v6
      - name: Build HTML using Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./report
          destination: ./_site
      - name: Upload pages
        uses: actions/upload-pages-artifact@v5
        with:
          path: '_site/'

  deploy:
    needs: sbom-scan

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
