name: SBOM Security Scan

on: workflow_dispatch

jobs:
  sbom-scan:
    runs-on: ubuntu-latest
    name: SBOM scan
    steps:
      - uses: actions/checkout@v6
      - name: Install grype
        shell: bash
        run: |
          wget https://github.com/anchore/grype/releases/download/v0.116.1/grype_0.116.1_linux_amd64.deb
          sudo dpkg -i *.deb
          sudo apt-get update
          sudo apt-get install -y colorized-logs
      - name: Scan SBOM
        shell: bash
        run: |
          mkdir -p report
          sboms=$(ls *-sbom.cdx.json)
          while IFS= read -r sbom; do
            image=$(basename $sbom -sbom.cdx.json)
            echo "Scanning $image..."
            CLICOLOR_FORCE=true grype sbom:$sbom --file $image.txt --by-cve
            DISTRO=$(jq -r '.components[] | select(.name == "base-files") | .purl' $sbom | grep -o 'distro=[^&]*')
            if [[ "$DISTRO" = *"debian"* ]]; then
                # URL="https:\/\/security-tracker.debian.org\/tracker\/"
                URL="https:\/\/deb.freexian.com\/extended-lts\/tracker\/"
            elif [[ "$DISTRO" = *"ubuntu"* ]]; then
                URL="https:\/\/ubuntu.com\/security\/"
            else
                URL="https:\/\/www.cve.org\/CVERecord?id="
            fi
            cat $image.txt | ansi2html --title "CVE $image" --no-wrap --style 'a {color: white;}' | sed -E 's/(CVE-[0-9]{4}-[0-9]{4,7})/<a href="$URL\1">\1<\/a>/g' > report/$image.html
          done <<< "$sboms"
      - name: Generate Markdown File
        run: |
          echo "name: IMAGO Technologies SBOMs and Vulnerability Report" > report/_config.yml
          echo "title: null" >> report/_config.yml
          cat << 'EOF' > report/index.md
          ## Linux Images

          The SBOMs for Linux images are provided in CycloneDX JSON format.

          All SBOMs are scanned for known vulnerabilities on a regular basis using [grype](https://github.com/anchore/grype).
          The vulnerability report contains a table with affected packages and the CVE names. Each entry also contains a link to the
          Security Bug Tracker of the used Linux distribution which provides more information.

          EOF
          echo "| Linux Image | SBOM | Vulnerability Report ($(date --rfc-3339=date)) |" >> report/index.md
          echo "| :--- | :--- | :--- |" >> report/index.md
          sboms=$(ls *-sbom.cdx.json)
          while IFS= read -r sbom; do
            image=$(basename $sbom -sbom.cdx.json)
            echo "|$image|[$sbom](https://github.com/IMAGO-Technologies/sbom-scan/blob/master/$sbom)|[$image]($image.html)|" >> report/index.md
          done <<< "$sboms"
      - name: Setup Pages Metadata
        uses: actions/configure-pages@v5
      - name: Build HTML using Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./report
          destination: ./_site
      - name: Upload pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site/'

  deploy:
    needs: sbom-scan

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
